FEEDS = [
    # ─── AUSTRALIAN DOMESTIC & BUSINESS ───────────────────────────
    {
        "name": "ABC News AU",
        "domain": "abc.net.au",
        "url": "https://www.abc.net.au/news/feed/51120/rss.xml",
        "region": "AU",
        "category": "Broadsheet",
        "weight": 8,
    },
    {
        "name": "ABC Business",
        "domain": "abc.net.au",
        "url": "https://www.abc.net.au/news/feed/46182/rss.xml",
        "region": "AU",
        "category": "Economy",
        "weight": 9,
    },
    {
        "name": "The Age Business",
        "domain": "theage.com.au",
        "url": "https://www.theage.com.au/rss/business.xml",
        "region": "AU",
        "category": "Economy",
        "weight": 9,
    },
    {
        "name": "Sydney Morning Herald",
        "domain": "smh.com.au",
        "url": "https://www.smh.com.au/rss/feed.xml",
        "region": "AU",
        "category": "Broadsheet",
        "weight": 7,
    },
    {
        "name": "The Guardian Australia",
        "domain": "theguardian.com",
        "url": "https://www.theguardian.com/australia-news/rss",
        "region": "AU",
        "category": "Broadsheet",
        "weight": 7,
    },

    # ─── GLOBAL ECONOMIC & BROADSHEET ────────────────────────────
    {
        "name": "Wall Street Journal Markets",
        "domain": "wsj.com",
        "url": "https://feeds.a.dj.com/rss/RSSMarketsMain.xml",
        "region": "GLOBAL",
        "category": "Economy",
        "weight": 10,
    },
    {
        "name": "WSJ World News",
        "domain": "wsj.com",
        "url": "https://feeds.a.dj.com/rss/RSSWorldNews.xml",
        "region": "GLOBAL",
        "category": "Broadsheet",
        "weight": 9,
    },
    {
        "name": "MarketWatch Top Stories",
        "domain": "marketwatch.com",
        "url": "https://feeds.content.dowjones.io/public/rss/mw_topstories",
        "region": "GLOBAL",
        "category": "Economy",
        "weight": 8,
    },
    {
        "name": "BBC World News",
        "domain": "bbc.com",
        "url": "https://feeds.bbci.co.uk/news/world/rss.xml",
        "region": "GLOBAL",
        "category": "Broadsheet",
        "weight": 8,
    },
    {
        "name": "CNBC International Economy",
        "domain": "cnbc.com",
        "url": "https://search.cnbc.com/rs/search/view.html?partnerId=2000&keywords=economy&sort=date",
        "region": "GLOBAL",
        "category": "Economy",
        "weight": 8,
    },
    {
        "name": "The Economist",
        "domain": "economist.com",
        "url": "https://www.economist.com/finance-and-economics/rss.xml",
        "region": "GLOBAL",
        "category": "Economy",
        "weight": 9,
    },
]